%date 2013-11-30
%author Larry Niven
%rating 1
%endnote In a more just universe, Speaker's plan succeeded.

Larry Niven's *Ringworld* (1970) is hailed as an all-time classic of the
science fiction genre, and won both *Hugo* and *Nebula* awards. It has alien
megastructures, interesting speculative technology, sinister alien plots,
apocalyptic socio-technological collapse, and aliens that *aren't* just human
cultural stereotypes in rubber suits. It inspired the *Halo* video game
franchise, and it has had such an impact on the genre that its influences made
their way into innumerable later works. 

I hated it.

What follows is an attempt to articulate *why* I hated it. I'm not going to
bother with a full plot summary; you can easily find one
[elsewhere](http://en.wikipedia.org/wiki/Ringworld). 

# The Awesome

I'm going to have to start out by saying that I think the titular Ringworld is
an absolutely *awesome* idea. It's a gigantic, circular section of a Dyson
sphere entirely encircling a central star, its inner surface a single giant
habitable area the size of *Earth's entire orbit*. Spinning around its sun to
create artificial gravity, it has its own oceans, atmosphere, continents and
biosphere. With a surface area roughly three million times larger than that of
Earth, it can support a population of *quadrillions*. So many interesting
stories could be told about life in such a place that an entire series of cool
science fiction stories could easily be set on the Ringworld - and yet, this
one is just a part of a much larger universe (Niven's "Known Space" setting)
with a fantastically rich history and biology.

I *wanted* to like *Ringworld*. How could I *not*?

# The Awful
Unfortunately, of all those cool stories that could potentially take place on
the Ringworld, *Ringworld* itself is not one. Rather, it's a jumbled messy
parade of nonsensical bullshit plot contrivances, disappointing clichés, sexist
dreck and painfully unlikable characters, and reads more like bad fan fiction
than like an award-winning novel.

The plot? Basically, there isn't one. Four annoying stereotypes travel to the
Ringworld, crash their ship into it, slog around on a small slice of its
surface, have some anticlimactic fights with the natives, and leave again. The
Ringworld itself - an idea with so much potential - becomes a colossal
disappointment.  Rather than being the site of an appropriately alien
environment and culture, it's full of Earth-like vegetation and populated by
pre-industrial humans who wander around with swords and spears, presumably so
we can have some cool pseudo-fantasy sword fights and stuff. The first third
of the book is all buildup - gathering the crew, observing the Ringworld from
afar, preparing the journey - but there's no payoff. For a so unique and
exotic type of setting with so much potential, the Ringworld manages to seem
downright *provincial*.

And then there's the characters. I hate them. Every single one of them.  Our
200-year-old protagonist, Louis Wu, is equal parts James Bond, Bruce Lee and
Indiana Jones: A wealthy, popular, brilliant, scientifically apt, physically
fit Übermensch who has sex with every female character in the book at some
point or other. He seems like something a 15-year-old might dream up for an
old-school tabletop RPG if he had telekinetic control of the dice during
character generation. 

Our alien characters are Speaker-to-Animals, a proud honor-bound Cat Klingon
(sorry, a kzin), and Nessus, a superintelligent insane Puppeteer (a race of
paranoid, extremely intelligent herbivorous herd animals), the latter of whom
is both nominally the leader of the expedition and the only character in the
story I found even slightly compelling. The two alien characters basically
carry all the interesting character interaction in the book: Nessus is a
secretive, sly manipulator whose real intentions the other characters can
never quite guess, and Speaker wants to murder the rest and make off in 
their spaceship. I can't say I blame him.

The final member of our crack team of interstellar scientific explorers is
Teela Brown: A young, vapid bimbo with no life experience and no useful skills,
who is *literally* brought along as a combination good luck charm and sex
companion for a man 180 years her senior. Cue toe-curlingly, cringe-inducingly
awful sex scenes that read as if they were written by the aforementioned
15-year-old desperately tending to a raging boner. Teela's only roles in the
story are as a sex object, as a receptacle of awkward expository monologue by
our omnicompetent protagonist, and as a walking deus ex machina.

Far be it from me to say that [Larry Niven is a misogynistic
troglodyte](http://www.rawbw.com/~svw/superman.html), but really, the blatant
sexism on display in *Ringworld* is so ridiculously, embarrassingly over the
top that it stands out even for 1970s science fiction. At one point, Teela
breaks down from "hysteria" (sic) due to the abrupt switch between day and
night on the Ringworld.  Towards the end of the story, she actually *asks
Louis to sell her as a sex slave* to a wandering barbarian warrior. The only
other named female character in *Ringworld* is Prill, who is literally a space
prostitute: A former crewmember on a Ringworld Engineer vessel, her shipboard
task was (along with the two other female crew members on the ship) to
sexually service the 27 male crew members. There is literally not *one* female
character in the entire story who has any discernible skill set or competence
apart from sexually servicing male characters. In both the kzin and Puppeteer
species, the females are actually *non-sentient*. 

I absolutely hated the ridiculous plot contrivance of Teela's luck. She was
chosen for the mission because the Puppeteers (who discovered the Ringworld and
financed the expedition to explore it) believe that luck is a genetically
hereditary trait, to such a degree that they have actually manipulated human
reproductive policies in order to breed particularly lucky humans. This is such
an obviously stupid plot contrivance that *the characters themselves call
bullshit on it* - and still, "the luck of Teela Brown" is used to explain
everything from surviving a nasty run-in with automated security systems to why
they went to the Ringworld in the first place. 

# Conclusion
*Ringworld* is a genuine piece of bad fiction. 

The fact that it's also the winner of multiple awards and lauded as a classic
in the genre is an unfortunate symptom of the ugly side of the Literature of
Ideas. The basic *idea* explored in *Ringworld* (that is, the Ringworld itself)
is interesting, well-thought-out, wonderfully detailed, and kept more or less
scientifically plausible given the constraints of the universe it takes place
in. Unfortunately, the plot and the characters seem like the literary
equivalent of an atrophied vestigial organ, and the treatment of female
characters is downright contemptible. 

Deriving a story from a cool idea, a neat gadget or a fantastic setting,
however, is also usually the hallmark of *good* science fiction - as well as
good fantasy, for that matter: J.R.R. Tolkien famously created the entire *Lord
of the Rings* stories and world starting from the Elvish language. 

What makes *Ringworld* awful isn't the "gadget-driven" narrative or any
scientific blunders in the setting, it's that the fantastic setting is
used to tell an awful story featuring awful characters doing awful things.
