(html (@ (lang (%data lang)))
  (head
    (meta (@ (name "author") (content "Simon Kongshøj")))
    (meta (@ (name "generator") (content "Plutonium")))
    (meta (@ (name "viewport") (content "width=device-width, initial-scale=1")))
    (%data meta)
    (link (@ (rel "stylesheet") (type "text/css") (href "css/style.css")))
    (title (%data header-title)))
  (body
    (div (@ (id "topmatter"))
         (a (@ (href "index.html")) "My glorious website!"))
    (div (@ (id "main") (class (%data pageclass)))
      (div (@ (id "sidebar"))
           (div 
                (%data sidebar)
                (div (@ (class "sidebar-module-outer"))
                     (div (@ (class "sidebar-module"))
                       (%data date)
                       (%data author)
                       (%data rating)))
                (div (@ (class "sidebar-module-outer"))
                     (div (@ (class "sidebar-module"))
                          (%data related)))))
      (div (@ (id "content"))
        (%data title)
        (%data content)
        (div (@ (id "breaker")) &nbsp\;)))
    (div (@ (id "bottommatter"))
        (a (@ (href "Plutonium.html"))
           "Powered by Plutonium"))))
